### PR TITLE
User dashboard

### PR DESCRIPTION
**Pull request by louiselmps**
-Shows user information in dahsboard and profile
-Can update user info in settings
-Words learned page is done/ finished
-Created activity model

### CODE REVIEW

**Review by inahsanjuan — CHANGES_REQUESTED** [review]
OK
- Layout is okay
- Code structure is good (almost same as mine actually)

Comments
- This drop down is being displayed but not working: https://prnt.sc/msvy1v, this is not a requirement in your project. But if you want to finish this, please make it work in this PR



For now this is okay, but please make your PRs and schedules be more organized next time.
- Activity model is created, but not being used?
- Words learned and dashboard in your schedule was separate
- Update profile is a total different function, you could create a different task in your schedule

**Comment by louiselmps** [comment]
Yes, i took inspiration from your layout from the sample site, so i kind of followed the layout same as yours. From there, i learned about bootstrap flex and using the correct grid columns. Thank you, for the positive review. I actually had difficulty as how i'm going to do the dropdown like if im going to do javascript but after numerous searches,  i found that there's a rails way on doing it by using the select_tag :)

I'm sorry that i kind of merged the functionalities in one PR and not follow the schedule. I'll try to take note of that next time :D

**Comment by louiselmps** [comment]
Dropdown works completely fine in my end, it shows the assigned words under a certain category when clicked. A little refreshing might help to get it work.

**Comment by inahsanjuan** [comment]
> Dropdown works completely fine in my end, it shows the assigned words under a certain category when clicked. A little refreshing might help to get it work.

@louiselumapas Yes, I can confirm it worked when refreshed.... Can you please fix this one?

Please observe the error in console log
image

**Pull request merged**
